# Generated by Django 4.0.3 on 2022-03-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, help_text='Friends relations', to='accounts.profile'),
        ),
    ]
