# Generated by Django 4.0.3 on 2022-03-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(blank=True, help_text='Zipcode field', max_length=10, null=True),
        ),
    ]
