# Generated by Django 4.0.3 on 2022-03-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_zipcode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('user', 'is_friend_of')},
        ),
    ]
