# Generated by Django 4.0.3 on 2022-03-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_friend_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
